services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  timescaledb:
    image: timescale/timescaledb-ha:pg16-all
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: changelog_db
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./init-scripts/timescaledb:/docker-entrypoint-initdb.d
    depends_on:
      - ollama

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-seed:
    build:
      context: ./init-scripts/mongodb/
      dockerfile: Dockerfile
    links:
      - mongodb
    depends_on:
      - mongodb

volumes:
  ollama_data:
  timescale_data:
  mongo_data:
