services:
  trading_my_sql:
    build:
      context: .
      dockerfile_inline: |-
        FROM ghcr.io/hasura/ndc-jvm-mysql:v0.1.0
        COPY ./ /etc/connector
    develop: {}
    env_file:
      - .env.local
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: "8084"
        protocol: tcp
