services:
  app_commit_history:
    build:
      context: .
      dockerfile_inline: |-
        FROM ghcr.io/hasura/ndc-postgres:v1.0.1
        COPY ./ /etc/connector
    develop:
      watch:
        - path: ./
          action: sync+restart
          target: /etc/connector
    environment:
      CONNECTION_URI: $APP_COMMIT_HISTORY_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_COMMIT_HISTORY_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: $APP_COMMIT_HISTORY_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      OTEL_SERVICE_NAME: $APP_COMMIT_HISTORY_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: "9655"
        protocol: tcp
